### ISSUE TITLE
Example with TabBar and multiple scenes

### ISSUE THREAD

**Issue by ranyefet** [pressly/scene-router#12]
Hello,

This library seems interesting... I was wondering If you could provide and example for an App that uses `TabBar` where each Tab has it's own navigation stack and have a way to control the navigation stack of each tab.

Is it possible?

Thanks,
Ran.

**Comment by alinz** [comment]
@ranyefet give me couple of days since I'm in the middle of something at the moment. I will keep you posted.

**Comment by sunny-g** [comment]
@alinz were you able to come up with an example of this?

**Comment by tclain** [comment]
+1

**Comment by alinz** [comment]
@sunny-g, @ranyefet and @tclain, version 1.2.0 supports `AreaList` which a key component for building tabbar app using scene-router.

closing this, please reopen or continue the conversation if you need more details. Example has been provided.
