### ISSUE TITLE
prevent multiple goto or goback calls before the sceneDidFocus is called

### ISSUE THREAD

**Issue by alinz** [pressly/scene-router#16]

**Comment by alinz** [comment]
Prevent multiple calls to the same scene at the same time.

**Comment by sunny-g** [comment]
Not sure if my issue is related to this, but if I trigger a `goback` on the initial page, the property `__sceneInTransition__` stays `true`, preventing any other scene transitions from being initiated.

**Comment by alinz** [comment]
@sunny-g I might be able to prevent it but why would you call `goback` on initial page? just curious.

**Comment by sunny-g** [comment]
Haha @alinz you never would and I could always put in logic to make sure you couldn't click a back button on the home page, but it seemed like incorrect behavior.

I have a few other unrelated questions, can I ask them here or should I open issues?

**Comment by alinz** [comment]
@sunny-g thank you for using my project. I would love you hear about them. I would be nice to create a separate issue for each one of them.
