### ISSUE TITLE
Transition hooks?

### ISSUE THREAD

**Issue by sunny-g** [pressly/scene-router#18]
At the moment, I'm using [Cycle-React](https://github.com/pH200/cycle-react) with scene-router and while that's introducing a few issues on its own (mainly having to do with passing global state as props to any and all scene-rendered components), this issue is about there not being an ability to add hooks to any transitions. 

For example, I wouldn't want a user to go to their profile page if they weren't logged in. Right now, I'm having to write my own wrapper around the `getScene` function that exposes new `goto` methods that will intercept those calls and make a decision about where to route based on their authenticated status.

Is there an easier way to do this? Is this what `onSceneChange` is for?

**Comment by alinz** [comment]
@sunny-g I have kind of the same issue with previous implementation that's why I redesigned it again. I made it simpler and instead of method's name I'm using props `sceneStatus` to pass around the lifecycle. it turns out to be a lot better solution. It might help you with Cycle-React thing.

**Comment by alinz** [comment]
closing this ticket. if you still using this library please try the new version and let me know. with the new release, scene-router becomes independent from any state management. We are using this with both mobx and redux and it turns out to be fully operational with both libraries.
