### ISSUE TITLE
Preserving component state

### ISSUE THREAD

**Issue by sunny-g** [pressly/scene-router#19]
If I navigate away from say, the Home page, then navigate to the Home page (but without going back), I'm rendering a fresh view of that page. While we have the ability to pass props to the Home page on the second render, its very likely that the component we're navigating away from won't know the Home page's original state/props.

Is the only way around this preserving the Home page's state somewhere else and then passing that state as props to re-populate the Home page on the second render?

**Comment by AleCaste** [comment]
I am experiencing the same problem too. Every time the method `goto` is called, the view we are navigating to is built from scratch and thus any previous state is lost.

**Comment by alinz** [comment]
This is a very hard problem to solve. There are so many possibility that might break the code. for that reason I decided to make it simple. Try to use state management such as redux or mobx.

**Comment by alinz** [comment]
@sunny-g `goto` is similar to `push to stack`. So if you push into the stack, a new component matches with that route will be created. You shouldn't worry about the performance. You can enhanced your performance by leveraging `SceneStatus` props lifecycle which `scene-router` is injecting to your app. Also as I mentioned before, you have to use some sort of state management to help you with your problem.

please try it, if you are still using `scene-router` and send me feedback. I'm closing this ticket but please continue the conversion if you have more questions.

@AleCaste ^
