### ISSUE TITLE
ios/android NavBar

### ISSUE THREAD

**Issue by jbrodriguez** [pressly/scene-router#21]
The component looks very clean and simple.

But how are you guys managing the navbars that are implicit in a mobile app ?

**Comment by alinz** [comment]
@jbrodriguez this is a pure scene management library which takes care of animation and states in your app. At Pressly, we built in house toll on top of this by using Mobx and maybe in the future we are releasing it as open source but right now it tights to our app.

**Comment by jbrodriguez** [comment]
ok, thanks for the reply
