### ISSUE TITLE
router.js wrong case sensitivity for importing area

### ISSUE THREAD

**Issue by mrphu3074** [pressly/scene-router#23]
https://github.com/pressly/scene-router/blob/master/lib/router.js#L6
I got error because file name is Area.js but router.js using 'area'
```
import { Area } from './area'
```

**Comment by alinz** [comment]
@mrphu3074 thanks, it was fixed! you can use v2.0.6

**Comment by awkaw** [comment]
Thank you!

Please! It requires more documentation. I do not know how to go to the 
next scene.


05.02.2017 11:03, Phu Nguyen пишет:

**Comment by mrphu3074** [comment]
They added a line `storeless, you can connect to redux or mobx stores`
So you have to use your custom store to change props in the main component.

**Comment by awkaw** [comment]
Thank you!


07.02.2017 11:00, Phu Nguyen пишет:

**Comment by alinz** [comment]
@awkaw I do have an example at the end of the README.md

```js
class App extends Component {
  constructor(props: any, context: any) {
    super(props, context)

    this.state = {
      area: "default",
      action: 'goto',
      config: {
        path: '/scenes/1'
      }
    }
  }

  render() {
    const { area, action, config } = this.state

    return (
      <Router
        area={area}
        action={action}
        config={config} />
    )
  }
}
```

you have to pass `goto` as action prop and a `config` object. the `path` property inside `config` object tells `Router` which scene you want to navigate to.
