### ISSUE TITLE
TransformError

### ISSUE THREAD

**Issue by lanqy** [pressly/scene-router#24]
Throw Error below:

Bundling `index.ios.js`  [development, non-minified, hmr disabled]  0.0% (0/376), failed.
error: bundling failed: "TransformError: /Applications/projects/routerDemo/index.ios.js: [BABEL] /Applications/projects/routerDemo/index.ios.js: Couldn't resolve extends clause of react-native/packager/react-packager/rn-babelrc.json in /Applications/projects/routerDemo/.babelrc"

**Comment by alinz** [comment]
@lanqy which version of react-native did you use?

**Comment by lanqy** [comment]
@alinz 

0.47.1 version , I init project with react-native CLI

this is the package.json :

  "dependencies": {
    "axios": "^0.16.2",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "mashape-oauth": "^0.1.71",
    "oauth": "^0.9.15",
    "react": "16.0.0-alpha.12",
    "react-native": "^0.47.1",
    "react-native-button": "^2.1.0",
    "react-native-navbar": "^1.8.0",
    "react-native-redux-router": "^1.0.7",
    "react-native-storage": "^0.2.2",
    "react-native-tabs": "^1.0.9",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "scene-router": "^2.0.6"
  }

**Comment by pinkladywithcoco** [comment]
same problem...

**Comment by alinz** [comment]
closing this for now
