### ISSUE TITLE
Support for react-native 0.16.0-rc and android

### ISSUE THREAD

**Issue by jaysoo** [pressly/scene-router#9]
## Issues with react-native 0.16.0-rc
- Components with `opacity: 0` prevents click throughs. (happens on 0.15.0)
- Cannot touch through `<TouchableWithoutFeedback/>` (happens on 0.15.0)
  - This is probably because transparent components no longer allow touch throughs
    
    ```
      <View style={{flex: 1}}>
        <View style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
          <TouchableOpacity onPress={() => console.log('content pressed')}>
            <Text>You can try to press me but it will not work!</Text>
          </TouchableOpacity>
        </View>
        <TouchableWithoutFeedback onPress={() => console.log('overlay pressed')}>
          <View style={{ backgroundColor: 'transparent', position: 'absolute', top: 0, left: 0, bottom: 0, right: 0 }}/>
        </TouchableWithoutFeedback>
      </View>
    ```
## Issues with Android
- Components always have `overflow: 'hidden'` and this property cannot be changed. This means that components with `position: 'absolute'` need their parents to have dimensions or else they will not be shown.

**Comment by alinz** [comment]
This has been fixed since version 0.3.0.
